### ISSUE TITLE
Problem with dpdk-devbind

### ISSUE THREAD

**Issue by NEOAdvancedTechnology** [F-Stack/f-stack#335]
On EC2 Linux version 3.10.0-957.el7.x86_64 (mockbuild@x86-040.build.eng.bos.redhat.com) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) #1 SMP Thu Oct 4 20:48:51 UTC 2018, PRETTY_NAME="Red Hat Enterprise Linux Server 7.6 (Maipo)"

Working from the instructions at: https://github.com/F-Stack/f-stack/blob/master/doc/Launch_F-Stack_on_AWS_EC2_in_one_minute.md

[note - keeping eth0 "normal" for remote access, and eth1 as the F-Stack interface]

[root]# python /data/f-stack/dpdk/usertools/dpdk-devbind.py --bind=igb_uio eth1
Traceback (most recent call last):
  File "/data/f-stack/dpdk/usertools/dpdk-devbind.py", line 718, in <module>
    main()
  File "/data/f-stack/dpdk/usertools/dpdk-devbind.py", line 711, in main
    get_device_details(network_devices)
  File "/data/f-stack/dpdk/usertools/dpdk-devbind.py", line 273, in get_device_details
    dev_lines = check_output(["lspci", "-Dvmmnnk"]).splitlines()
  File "/data/f-stack/dpdk/usertools/dpdk-devbind.py", line 149, in check_output
    stderr=stderr).communicate()[0]
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by 5dplay** [comment]
Try install pciutils to support  command `lspci`?
 `yum install pciutils`

**Comment by NEOAdvancedTechnology** [comment]
That solved the problem, thanks!
