### ISSUE TITLE
sysctl and netstat crash, ifconfig work ok.

### ISSUE THREAD

**Issue by amjy** [F-Stack/f-stack#70]
setup centos 7.2
==
export FF_PATH=/root/f-stack
export FF_DPDK=${FF_PATH}/dpdk/x86_64-native-linuxapp-gcc

cd $FF_PATH

#echo 1024 > /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
echo 1024 > /sys/devices/system/node/node0/hugepages/hugepages-2048kB/nr_hugepages
echo 1024 > /sys/devices/system/node/node1/hugepages/hugepages-2048kB/nr_hugepages

mkdir /mnt/huge
mount -t hugetlbfs nodev /mnt/huge

echo 0 > /proc/sys/kernel/randomize_va_space

cd dpdk/tools/
modprobe uio
insmod ../x86_64-native-linuxapp-gcc/kmod/igb_uio.ko
insmod ../x86_64-native-linuxapp-gcc/kmod/rte_kni.ko

python dpdk-devbind.py --status
ifconfig eth1 down
python dpdk-devbind.py --bind=igb_uio eth1
python dpdk-devbind.py --status

./sysctl/sysctl -p0 -a
==

EAL: Could not mmap 12582912 bytes in /dev/zero to requested address [0x7ffff4000000]: 'No such file or directory'
PANIC in rte_eal_init():
Cannot init memory
10: [./sysctl/sysctl() [0x40369d]]
9: [/lib64/libc.so.6(__libc_start_main+0xf5) [0x7ffff6d29b15]]
8: [./sysctl/sysctl() [0x4039bc]]
7: [./sysctl/sysctl() [0x405d10]]
6: [./sysctl/sysctl(sysctl+0x57) [0x4071db]]
5: [./sysctl/sysctl() [0x407f14]]
4: [./sysctl/sysctl() [0x407e96]]
3: [./sysctl/sysctl() [0x410aa6]]
2: [./sysctl/sysctl() [0x4033b6]]
1: [./sysctl/sysctl() [0x41789a]]
已放弃

./netstat/netstat
==

EAL: Could not mmap 12582912 bytes in /dev/zero to requested address [0x7ffff4000000]: 'No such file or directory'
PANIC in rte_eal_init():
Cannot init memory
14: [./netstat/netstat() [0x403dfd]]
13: [/lib64/libc.so.6(__libc_start_main+0xf5) [0x7ffff6d29b15]]
12: [./netstat/netstat() [0x409eca]]
11: [./netstat/netstat() [0x40a344]]
10: [./netstat/netstat() [0x405497]]
9: [./netstat/netstat() [0x40535b]]
8: [./netstat/netstat() [0x42d118]]
7: [./netstat/netstat() [0x4257b6]]
6: [./netstat/netstat(sysctl+0x57) [0x4253db]]
5: [./netstat/netstat() [0x426114]]
4: [./netstat/netstat() [0x426096]]
3: [./netstat/netstat() [0x42eca6]]
2: [./netstat/netstat() [0x403b16]]
1: [./netstat/netstat() [0x435a9a]]
已放弃

gdb ./netstat/netstat
==

GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-80.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /root/f-stack/tools/netstat/netstat...done.
(gdb) r
Starting program: /root/f-stack/tools/./netstat/netstat 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
EAL: Could not mmap 12582912 bytes in /dev/zero to requested address [0x7ffff4000000]: 'No such file or directory'
PANIC in rte_eal_init():
Cannot init memory
14: [/root/f-stack/tools/./netstat/netstat() [0x403dfd]]
13: [/lib64/libc.so.6(__libc_start_main+0xf5) [0x7ffff6d29b15]]
12: [/root/f-stack/tools/./netstat/netstat() [0x409eca]]
11: [/root/f-stack/tools/./netstat/netstat() [0x40a344]]
10: [/root/f-stack/tools/./netstat/netstat() [0x405497]]
9: [/root/f-stack/tools/./netstat/netstat() [0x40535b]]
8: [/root/f-stack/tools/./netstat/netstat() [0x42d118]]
7: [/root/f-stack/tools/./netstat/netstat() [0x4257b6]]
6: [/root/f-stack/tools/./netstat/netstat(sysctl+0x57) [0x4253db]]
5: [/root/f-stack/tools/./netstat/netstat() [0x426114]]
4: [/root/f-stack/tools/./netstat/netstat() [0x426096]]
3: [/root/f-stack/tools/./netstat/netstat() [0x42eca6]]
2: [/root/f-stack/tools/./netstat/netstat() [0x403b16]]
1: [/root/f-stack/tools/./netstat/netstat() [0x435a9a]]

Program received signal SIGABRT, Aborted.
0x00007ffff6d3d5f7 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.17-105.el7.x86_64 libgcc-4.8.5-4.el7.x86_64 openssl-libs-1.0.1e-51.el7_2.7.x86_64 zlib-1.2.7-15.el7.x86_64
(gdb) bt
#0  0x00007ffff6d3d5f7 in raise () from /lib64/libc.so.6
#1  0x00007ffff6d3ece8 in abort () from /lib64/libc.so.6
#2  0x0000000000403b1b in __rte_panic ()
#3  0x000000000042eca6 in rte_eal_init ()
#4  0x0000000000426096 in ff_ipc_init () at ff_ipc.c:68
#5  0x0000000000426114 in ff_ipc_msg_alloc () at ff_ipc.c:87
#6  0x00000000004253db in sysctl (name=0x7fffffffe1a0, namelen=2, old=0x7fffffffe200, oldlenp=0x7fffffffe1f8, new=0x443158, 
    newlen=20) at sysctl.c:45
#7  0x00000000004257b6 in sysctlnametomib (name=0x443158 "net.inet.tcp.pcblist", mibp=0x7fffffffe200, sizep=0x7fffffffe1f8)
    at sysctlnametomib.c:55
#8  0x000000000042d118 in sysctlbyname (name=0x443158 "net.inet.tcp.pcblist", oldp=0x0, oldlenp=0x7fffffffe2a8, newp=0x0, 
    newlen=0) at sysctlbyname.c:27
#9  0x000000000040535b in pcblist_sysctl (proto=6, name=0x446fe5 "tcp", bufp=0x7fffffffe348, istcp=1) at inet.c:118
#10 0x0000000000405497 in protopr (off=0, name=0x446fe5 "tcp", af1=0, proto=6) at inet.c:348
#11 0x000000000040a344 in printproto (tp=0x65d700 <protox>, name=0x446fe5 "tcp", first=0x7fffffffe437) at main.c:687
#12 0x0000000000409eca in main (argc=0, argv=0x7fffffffe550) at main.c:556
(gdb)

**Comment by amjy** [comment]
Fixxed: #73

**Comment by amjy** [comment]
Fixxed: #73
