### ISSUE TITLE
on high connections rate, kevent is crashing on zone_release 

### ISSUE THREAD

**Issue by rajeshwarp2002** [F-Stack/f-stack#757]
(gdb) bt
#0  0x0000000001ab3802 in zone_release ()
#1  0x0000000001ab32ad in zone_free_item ()
#2  0x000000000059cc7c in cache_alloc ()
#3  0x000000000059cf54 in cache_alloc_retry ()
#4  0x000000000059d08f in bucket_alloc ()
#5  0x000000000059d176 in cache_free.isra.18.constprop.20 ()
#6  0x0000000001ab6d0b in uma_zfree_arg ()
#7  0x000000000059cc7c in cache_alloc ()
#8  0x000000000059cf54 in cache_alloc_retry ()
#9  0x00000000019b2b6f in kqueue_register.part.13 ()
#10 0x00000000019b2e7f in kqueue_kevent ()
#11 0x00000000019b3a6d in kern_kevent_fp ()
#12 0x00000000019b3b28 in kern_kevent ()
#13 0x00000000019a6a14 in ff_kevent_do_each ()
#14 0x00000000019a6a51 in ff_kevent ()

**Comment by rajeshwarp2002** [comment]
this got fixed by following commit
https://github.com/F-Stack/f-stack/commit/5ed6baeedbf9750e3a14c2bbd4f9aa2481f16d0f
